name: GitHub Actions Demo
run-name: Build and Publish
on: [push]
jobs:
  Build-Extension:
    runs-on: ubuntu-latest
    steps:
      - run: ls -lash
      - name: Install Deps
        run: npm install
      - name: Package Extension
        run: vsce package
